# SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT
version: 2
project_name: "openchami-logq"
before:
  hooks:
    - go mod download -C compactor
    - go mod download -C query

builds:
  - id: "compactor"
    binary: "openchami-logq-compactor"
    dir: "compactor"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "

  - id: "query"
    binary: "openchami-logq-query"
    dir: "query"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
    ldflags:
      - "-s -w -X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "


dockers_v2:
  - id: "compactor"
    ids:
      - "compactor"
    use: buildx
    images:
      - "ghcr.io/openchami/openchami-logq-compactor"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "openchami-logq-compactor"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    extra_files:
      - "LICENSES/MIT.txt"
      - "README.md"
    dockerfile: "compactor/Dockerfile"
    build_flag_templates:
      - "--pull"

  - id: "query"
    ids:
      - "query"
    use: buildx
    images:
      - "ghcr.io/openchami/openchami-logq-query"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "openchami-logq-query"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    extra_files:
      - "LICENSES/MIT.txt"
      - "README.md"
    dockerfile: "query/Dockerfile"
    build_flag_templates:
      - "--pull"

archives:
  - id: "compactor"
    builds:
      - "compactor"
    name_template: >-
      {{ .ProjectName }}-compactor_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSES/MIT.txt
      - README.md

  - id: "query"
    builds:
      - "query"
    name_template: >-
      {{ .ProjectName }}-query_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSES/MIT.txt
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  disable: "{{ if eq .Env.IS_PR_BUILD \"true\" }}true{{ else }}false{{ end }}"
  github:
    owner: OpenCHAMI
    name: legendary-funicular
  name_template: 'v{{ .Version }}'
  prerelease: auto
  mode: replace


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
