# SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
#
# SPDX-License-Identifier: MIT

# Forward all openchami syslog messages to a remote server using UDP.
lookup_table(name="openchami-services" file="/etc/rsyslog.d/openchami-service-lookup.json")
if lookup("openchami-services", $programname) == "1" then {
    action(
        type="omfwd"
        protocol="udp"
        target="127.0.0.1"
        port="1514"
        action.resumeRetryCount="-1"     # infinite retries on insert failure
        queue.type="LinkedList"          # use asynchronous processing
        queue.filename="fwdvector"       # enables disk assistance
        queue.saveOnShutdown="on"
    )
}
